name: Build, Test, and Push Native Compiler Binaries
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Windows Dev Environment (skipped on Linux and macOS)
      uses: seanmiddleditch/gha-setup-vsdevenv@master
      if: ${{ matrix.platform == 'windows-latest' }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn
    - name: Remove OS Restrictions
      run: node ./tasks/remove-os-restrictions.js
    - name: Upgrade Packages to Specified Closure Version
      run: node ./tasks/bump-version.js
    - name: Compile Native Binary
      run: yarn build
    - name: Link Native Binary
      run: |
        (yarn link --cwd packages/google-closure-compiler-osx)
        (yarn link --cwd packages/google-closure-compiler-linux)
        (yarn link --cwd packages/google-closure-compiler-windows)
        (yarn link "@ampproject/google-closure-compiler-osx" --cwd packages/google-closure-compiler)
        (yarn link "@ampproject/google-closure-compiler-linux" --cwd packages/google-closure-compiler)
        (yarn link "@ampproject/google-closure-compiler-windows" --cwd packages/google-closure-compiler)
    - name: Test Changes
      run: yarn test
    - name: Push Native Binary for ${{ matrix.platform }}
      if: ${{ github.event_name == 'push' }}
      run: node ./tasks/push-binary.js
