name: Build Binaries

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        lfs: true
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.x' # The JDK version to make available on the path.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install
    - name: Remove OS Restrictions
      run: node ./tasks/remove-os-restrictions.js
    - name: Upgrade Packages to Specified Closure Version
      run: node ./tasks/bump-version.js
    - name: Compile Native Binary
      run: yarn build
    - name: Link Native Binary
      run: |
        (cd packages/google-closure-compiler-osx && yarn link)
        (cd packages/google-closure-compiler-linux && yarn link)
        (cd packages/google-closure-compiler && yarn link "@kristoferbaxter/google-closure-compiler-osx")
        (cd packages/google-closure-compiler && yarn link "@kristoferbaxter/google-closure-compiler-linux")
    - name: Test Changes
      run: yarn test
    - name: Push Changes
      uses: kristoferbaxter/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}