name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-test-push:
    if: ${{ !contains(github.event.head_commit.message, 'skip CI') }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Windows Dev Environment (skipped on Linux and macOS)
      uses: seanmiddleditch/gha-setup-vsdevenv@master
      if: ${{ matrix.platform == 'windows-latest' }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn
    - name: Compile Native Binary
      run: yarn build
    - name: Link Native Binary
      run: yarn link-native
    - name: Test Changes
      run: yarn test
    - name: Push Native Binary for ${{ matrix.platform }}
      run: node ./tasks/push-binary.js
  update-versions:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Update Package Versions
        run: node ./tasks/update-versions.js
